export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_TABLE_PRICES = 'GET_TABLE_PRICES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_TABLE_PRICE = 'SELECT_TABLE_PRICE';
