export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_BRANDS = 'GET_BRANDS';
export const SELECT_BRAND= 'SELECT_BRAND';
