export const ADD_INVOICE = 'ADD_INVOICE';
export const CHANGE_ACTIVE_KEY = 'CHANGE_ACTIVE_KEY';
export const ADD_TAB = 'ADD_TAB';
export const REMOVE_TAB = 'REMOVE_TAB';
export const CHANGE_TOTAL_NUM_RETURNS = 'CHANGE_TOTAL_NUM_RETURNS';
export const CHANGE_FEE = 'CHANGE_FEE';
export const CHANGE_TOTAL_PAID = 'CHANGE_TOTAL_PAID';
