export const ADD_INVOICE = 'ADD_INVOICE';
export const CHANGE_TOTAL_NUM_RETURNS = 'CHANGE_TOTAL_NUM_RETURNS';
export const CHANGE_FEE = 'CHANGE_FEE';
export const CHANGE_TOTAL_PAID = 'CHANGE_TOTAL_PAID';

